//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: battle.proto
// Note: requires additional types generated from: prototype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleClientReady")]
  public partial class BattleClientReady : global::ProtoBuf.IExtensible
  {
    public BattleClientReady() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_CLIENT_READY_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_CLIENT_READY_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleAllReadyNtf")]
  public partial class BattleAllReadyNtf : global::ProtoBuf.IExtensible
  {
    public BattleAllReadyNtf() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_ALL_READY_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_ALL_READY_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _seed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seed
    {
      get { return _seed; }
      set { _seed = value; }
    }
    private uint _frame_sec = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"frame_sec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frame_sec
    {
      get { return _frame_sec; }
      set { _frame_sec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInitInfo")]
  public partial class BattleInitInfo : global::ProtoBuf.IExtensible
  {
    public BattleInitInfo() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_INIT_INFO_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_INIT_INFO_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _row;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _column;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint column
    {
      get { return _column; }
      set { _column = value; }
    }
    private uint _uid1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"uid1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid1
    {
      get { return _uid1; }
      set { _uid1 = value; }
    }
    private string _name1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name1
    {
      get { return _name1; }
      set { _name1 = value; }
    }
    private uint _uid2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"uid2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid2
    {
      get { return _uid2; }
      set { _uid2 = value; }
    }
    private string _name2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"name2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name2
    {
      get { return _name2; }
      set { _name2 = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _mines = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"mines", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mines
    {
      get { return _mines; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleOpenMineReq")]
  public partial class BattleOpenMineReq : global::ProtoBuf.IExtensible
  {
    public BattleOpenMineReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_OPEN_MINE_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_OPEN_MINE_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _row = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _column = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint column
    {
      get { return _column; }
      set { _column = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleOpenMineRet")]
  public partial class BattleOpenMineRet : global::ProtoBuf.IExtensible
  {
    public BattleOpenMineRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_OPEN_MINE_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_OPEN_MINE_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _row = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _column = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint column
    {
      get { return _column; }
      set { _column = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleOpenMineNtf")]
  public partial class BattleOpenMineNtf : global::ProtoBuf.IExtensible
  {
    public BattleOpenMineNtf() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_OPEN_MINE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_OPEN_MINE_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _row = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint row
    {
      get { return _row; }
      set { _row = value; }
    }
    private uint _column = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint column
    {
      get { return _column; }
      set { _column = value; }
    }
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleResult")]
  public partial class BattleResult : global::ProtoBuf.IExtensible
  {
    public BattleResult() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_RESULT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_RESULT_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _winner = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong winner
    {
      get { return _winner; }
      set { _winner = value; }
    }
    private uint _bombrow = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bombrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bombrow
    {
      get { return _bombrow; }
      set { _bombrow = value; }
    }
    private uint _bombcolumn = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bombcolumn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bombcolumn
    {
      get { return _bombcolumn; }
      set { _bombcolumn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}