//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: blob.proto
namespace Bin
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheBladeData")]
  public partial class CacheBladeData : global::ProtoBuf.IExtensible
  {
    public CacheBladeData() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _userid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _star = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _quality = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _strengthlv = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"strengthlv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint strengthlv
    {
      get { return _strengthlv; }
      set { _strengthlv = value; }
    }
    private uint _equipindex = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private ulong _liberationnode = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"liberationnode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong liberationnode
    {
      get { return _liberationnode; }
      set { _liberationnode = value; }
    }
    private uint _skillid1 = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"skillid1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid1
    {
      get { return _skillid1; }
      set { _skillid1 = value; }
    }
    private uint _level1 = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"level1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level1
    {
      get { return _level1; }
      set { _level1 = value; }
    }
    private uint _skillid2 = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"skillid2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid2
    {
      get { return _skillid2; }
      set { _skillid2 = value; }
    }
    private uint _level2 = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"level2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level2
    {
      get { return _level2; }
      set { _level2 = value; }
    }
    private uint _skillid3 = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"skillid3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid3
    {
      get { return _skillid3; }
      set { _skillid3 = value; }
    }
    private uint _level3 = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"level3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level3
    {
      get { return _level3; }
      set { _level3 = value; }
    }
    private uint _bklv = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"bklv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bklv
    {
      get { return _bklv; }
      set { _bklv = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheSoulData")]
  public partial class CacheSoulData : global::ProtoBuf.IExtensible
  {
    public CacheSoulData() {}
    
    private ulong _thisid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private ulong _userid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _soulid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"soulid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint soulid
    {
      get { return _soulid; }
      set { _soulid = value; }
    }
    private ulong _exp = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _star = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _equipindex = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private uint _grade = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheEffectData")]
  public partial class CacheEffectData : global::ProtoBuf.IExtensible
  {
    public CacheEffectData() {}
    
    private uint _logic = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"logic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint logic
    {
      get { return _logic; }
      set { _logic = value; }
    }
    private uint _param1 = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _times = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _fixtype = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fixtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint fixtype
    {
      get { return _fixtype; }
      set { _fixtype = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private uint _orivalue = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"orivalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint orivalue
    {
      get { return _orivalue; }
      set { _orivalue = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _params = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> @params
    {
      get { return _params; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheBuffData")]
  public partial class CacheBuffData : global::ProtoBuf.IExtensible
  {
    public CacheBuffData() {}
    
    private uint _buffid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buffid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint buffid
    {
      get { return _buffid; }
      set { _buffid = value; }
    }
    private ulong _starttime = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong starttime
    {
      get { return _starttime; }
      set { _starttime = value; }
    }
    private uint _layer = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint layer
    {
      get { return _layer; }
      set { _layer = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.CacheEffectData> _effects = new global::System.Collections.Generic.List<Bin.CacheEffectData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"effects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheEffectData> effects
    {
      get { return _effects; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheAvatar")]
  public partial class CacheAvatar : global::ProtoBuf.IExtensible
  {
    public CacheAvatar() {}
    
    private uint _eye = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eye", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eye
    {
      get { return _eye; }
      set { _eye = value; }
    }
    private uint _nose = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint nose
    {
      get { return _nose; }
      set { _nose = value; }
    }
    private uint _mouth = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mouth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mouth
    {
      get { return _mouth; }
      set { _mouth = value; }
    }
    private uint _hair = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hair", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hair
    {
      get { return _hair; }
      set { _hair = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheCharbase")]
  public partial class CacheCharbase : global::ProtoBuf.IExtensible
  {
    public CacheCharbase() {}
    
    private ulong _userid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private Bin.CacheAvatar _avatar = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheAvatar avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private uint _lock = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lock", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint @lock
    {
      get { return _lock; }
      set { _lock = value; }
    }
    private uint _bp = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bp
    {
      get { return _bp; }
      set { _bp = value; }
    }
    private uint _title = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint title
    {
      get { return _title; }
      set { _title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheBlade")]
  public partial class CacheBlade : global::ProtoBuf.IExtensible
  {
    public CacheBlade() {}
    
    private Bin.CacheBladeData _base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheBladeData @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheSoul")]
  public partial class CacheSoul : global::ProtoBuf.IExtensible
  {
    public CacheSoul() {}
    
    private Bin.CacheSoulData _souls = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"souls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheSoulData souls
    {
      get { return _souls; }
      set { _souls = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheBuff")]
  public partial class CacheBuff : global::ProtoBuf.IExtensible
  {
    public CacheBuff() {}
    
    private Bin.CacheBuffData _buffs = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheBuffData buffs
    {
      get { return _buffs; }
      set { _buffs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheDress")]
  public partial class CacheDress : global::ProtoBuf.IExtensible
  {
    public CacheDress() {}
    
    private uint _dressid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dressid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dressid
    {
      get { return _dressid; }
      set { _dressid = value; }
    }
    private uint _lv = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private bool _isequip = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isequip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isequip
    {
      get { return _isequip; }
      set { _isequip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheSoulCore")]
  public partial class CacheSoulCore : global::ProtoBuf.IExtensible
  {
    public CacheSoulCore() {}
    
    private uint _maxhp = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private uint _patt = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"patt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint patt
    {
      get { return _patt; }
      set { _patt = value; }
    }
    private uint _pdef = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint pdef
    {
      get { return _pdef; }
      set { _pdef = value; }
    }
    private uint _catt = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"catt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint catt
    {
      get { return _catt; }
      set { _catt = value; }
    }
    private uint _cdef = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cdef
    {
      get { return _cdef; }
      set { _cdef = value; }
    }
    private uint _cpstren = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cpstren", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cpstren
    {
      get { return _cpstren; }
      set { _cpstren = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheScabbard")]
  public partial class CacheScabbard : global::ProtoBuf.IExtensible
  {
    public CacheScabbard() {}
    
    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private uint _bladeid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _lv = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CacheUserProto")]
  public partial class CacheUserProto : global::ProtoBuf.IExtensible
  {
    public CacheUserProto() {}
    
    private Bin.CacheCharbase _base = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheCharbase @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.CacheBlade> _blades = new global::System.Collections.Generic.List<Bin.CacheBlade>();
    [global::ProtoBuf.ProtoMember(2, Name=@"blades", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheBlade> blades
    {
      get { return _blades; }
    }
  
    private readonly global::System.Collections.Generic.List<Bin.CacheSoul> _souls = new global::System.Collections.Generic.List<Bin.CacheSoul>();
    [global::ProtoBuf.ProtoMember(3, Name=@"souls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheSoul> souls
    {
      get { return _souls; }
    }
  
    private readonly global::System.Collections.Generic.List<Bin.CacheDress> _dress = new global::System.Collections.Generic.List<Bin.CacheDress>();
    [global::ProtoBuf.ProtoMember(4, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheDress> dress
    {
      get { return _dress; }
    }
  
    private Bin.CacheSoulCore _soulcore = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"soulcore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.CacheSoulCore soulcore
    {
      get { return _soulcore; }
      set { _soulcore = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _title = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> title
    {
      get { return _title; }
    }
  
    private byte[] _unionname = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"unionname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] unionname
    {
      get { return _unionname; }
      set { _unionname = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.CacheScabbard> _scabbard = new global::System.Collections.Generic.List<Bin.CacheScabbard>();
    [global::ProtoBuf.ProtoMember(8, Name=@"scabbard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheScabbard> scabbard
    {
      get { return _scabbard; }
    }
  
    private readonly global::System.Collections.Generic.List<Bin.CacheBladeData> _grabmine = new global::System.Collections.Generic.List<Bin.CacheBladeData>();
    [global::ProtoBuf.ProtoMember(9, Name=@"grabmine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CacheBladeData> grabmine
    {
      get { return _grabmine; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemData")]
  public partial class ItemData : global::ProtoBuf.IExtensible
  {
    public ItemData() {}
    
    private ulong _thisid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _itemid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private uint _createtime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemList")]
  public partial class ItemList : global::ProtoBuf.IExtensible
  {
    public ItemList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.ItemData> _list = new global::System.Collections.Generic.List<Bin.ItemData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ItemData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemNotiTypeBlob")]
  public partial class ItemNotiTypeBlob : global::ProtoBuf.IExtensible
  {
    public ItemNotiTypeBlob() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _itemid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillData")]
  public partial class SkillData : global::ProtoBuf.IExtensible
  {
    public SkillData() {}
    
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillList")]
  public partial class SkillList : global::ProtoBuf.IExtensible
  {
    public SkillList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.SkillData> _list = new global::System.Collections.Generic.List<Bin.SkillData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SkillData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitQuestIDList")]
  public partial class SubmitQuestIDList : global::ProtoBuf.IExtensible
  {
    public SubmitQuestIDList() {}
    
    private readonly global::System.Collections.Generic.List<uint> _questid = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> questid
    {
      get { return _questid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestData")]
  public partial class QuestData : global::ProtoBuf.IExtensible
  {
    public QuestData() {}
    
    private uint _questid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DoingQuestList")]
  public partial class DoingQuestList : global::ProtoBuf.IExtensible
  {
    public DoingQuestList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.QuestData> _list = new global::System.Collections.Generic.List<Bin.QuestData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.QuestData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectData")]
  public partial class EffectData : global::ProtoBuf.IExtensible
  {
    public EffectData() {}
    
    private uint _logic_;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"logic_", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint logic_
    {
      get { return _logic_; }
      set { _logic_ = value; }
    }
    private uint _param1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _fixtype;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fixtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fixtype
    {
      get { return _fixtype; }
      set { _fixtype = value; }
    }
    private uint _value;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private uint _orivalue;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"orivalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint orivalue
    {
      get { return _orivalue; }
      set { _orivalue = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _params = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> @params
    {
      get { return _params; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuffData")]
  public partial class BuffData : global::ProtoBuf.IExtensible
  {
    public BuffData() {}
    
    private uint _buffid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buffid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buffid
    {
      get { return _buffid; }
      set { _buffid = value; }
    }
    private ulong _starttime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong starttime
    {
      get { return _starttime; }
      set { _starttime = value; }
    }
    private uint _layer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint layer
    {
      get { return _layer; }
      set { _layer = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.EffectData> _effects = new global::System.Collections.Generic.List<Bin.EffectData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"effects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.EffectData> effects
    {
      get { return _effects; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuffList")]
  public partial class BuffList : global::ProtoBuf.IExtensible
  {
    public BuffList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.BuffData> _buffs = new global::System.Collections.Generic.List<Bin.BuffData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.BuffData> buffs
    {
      get { return _buffs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyData")]
  public partial class CopyData : global::ProtoBuf.IExtensible
  {
    public CopyData() {}
    
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint status
    {
      get { return _status; }
      set { _status = value; }
    }
    private uint _fighttimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fighttimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fighttimes
    {
      get { return _fighttimes; }
      set { _fighttimes = value; }
    }
    private uint _resettimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"resettimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint resettimes
    {
      get { return _resettimes; }
      set { _resettimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyList")]
  public partial class CopyList : global::ProtoBuf.IExtensible
  {
    public CopyList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.CopyData> _list = new global::System.Collections.Generic.List<Bin.CopyData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.CopyData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SysMailConf")]
  public partial class SysMailConf : global::ProtoBuf.IExtensible
  {
    public SysMailConf() {}
    
    private string _sender = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _text = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.ItemNotiTypeBlob> _item = new global::System.Collections.Generic.List<Bin.ItemNotiTypeBlob>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ItemNotiTypeBlob> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailArgs")]
  public partial class MailArgs : global::ProtoBuf.IExtensible
  {
    public MailArgs() {}
    
    private readonly global::System.Collections.Generic.List<uint> _arg = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"arg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> arg
    {
      get { return _arg; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopData")]
  public partial class ShopData : global::ProtoBuf.IExtensible
  {
    public ShopData() {}
    
    private uint _shopid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shopid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shopid
    {
      get { return _shopid; }
      set { _shopid = value; }
    }
    private uint _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArenaShopData")]
  public partial class ArenaShopData : global::ProtoBuf.IExtensible
  {
    public ArenaShopData() {}
    
    private readonly global::System.Collections.Generic.List<Bin.ShopData> _shops = new global::System.Collections.Generic.List<Bin.ShopData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"shops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ShopData> shops
    {
      get { return _shops; }
    }
  
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharData")]
  public partial class CharData : global::ProtoBuf.IExtensible
  {
    public CharData() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillBase")]
  public partial class SkillBase : global::ProtoBuf.IExtensible
  {
    public SkillBase() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeBase")]
  public partial class BladeBase : global::ProtoBuf.IExtensible
  {
    public BladeBase() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _quality;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _strengthlv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"strengthlv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint strengthlv
    {
      get { return _strengthlv; }
      set { _strengthlv = value; }
    }
    private uint _releaselv;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"releaselv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint releaselv
    {
      get { return _releaselv; }
      set { _releaselv = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private uint _libernode1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"libernode1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint libernode1
    {
      get { return _libernode1; }
      set { _libernode1 = value; }
    }
    private uint _libernode2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"libernode2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint libernode2
    {
      get { return _libernode2; }
      set { _libernode2 = value; }
    }
    private uint _libernode3;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"libernode3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint libernode3
    {
      get { return _libernode3; }
      set { _libernode3 = value; }
    }
    private uint _libernode4;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"libernode4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint libernode4
    {
      get { return _libernode4; }
      set { _libernode4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BladeData")]
  public partial class BladeData : global::ProtoBuf.IExtensible
  {
    public BladeData() {}
    
    private Bin.BladeBase _base;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Bin.BladeBase @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.SkillBase> _skill = new global::System.Collections.Generic.List<Bin.SkillBase>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SkillBase> skill
    {
      get { return _skill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulData")]
  public partial class SoulData : global::ProtoBuf.IExtensible
  {
    public SoulData() {}
    
    private ulong _thisid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _soulid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"soulid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint soulid
    {
      get { return _soulid; }
      set { _soulid = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _star;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star; }
      set { _star = value; }
    }
    private uint _equipindex;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"equipindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint equipindex
    {
      get { return _equipindex; }
      set { _equipindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipInfo")]
  public partial class EquipInfo : global::ProtoBuf.IExtensible
  {
    public EquipInfo() {}
    
    private Bin.CharData _charbase;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charbase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Bin.CharData charbase
    {
      get { return _charbase; }
      set { _charbase = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.BladeData> _blade = new global::System.Collections.Generic.List<Bin.BladeData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"blade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.BladeData> blade
    {
      get { return _blade; }
    }
  
    private readonly global::System.Collections.Generic.List<Bin.SoulData> _soul = new global::System.Collections.Generic.List<Bin.SoulData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"soul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulData> soul
    {
      get { return _soul; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterRecord")]
  public partial class MonsterRecord : global::ProtoBuf.IExtensible
  {
    public MonsterRecord() {}
    
    private uint _copyid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"copyid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint copyid
    {
      get { return _copyid; }
      set { _copyid = value; }
    }
    private uint _dropid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dropid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dropid
    {
      get { return _dropid; }
      set { _dropid = value; }
    }
    private uint _times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _totaltimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"totaltimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totaltimes
    {
      get { return _totaltimes; }
      set { _totaltimes = value; }
    }
    private bool _isdrop;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isdrop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isdrop
    {
      get { return _isdrop; }
      set { _isdrop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterRecordInfo")]
  public partial class MonsterRecordInfo : global::ProtoBuf.IExtensible
  {
    public MonsterRecordInfo() {}
    
    private readonly global::System.Collections.Generic.List<Bin.MonsterRecord> _records = new global::System.Collections.Generic.List<Bin.MonsterRecord>();
    [global::ProtoBuf.ProtoMember(1, Name=@"records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MonsterRecord> records
    {
      get { return _records; }
    }
  
    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemCount")]
  public partial class ItemCount : global::ProtoBuf.IExtensible
  {
    public ItemCount() {}
    
    private uint _itemid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshShopList")]
  public partial class RefreshShopList : global::ProtoBuf.IExtensible
  {
    public RefreshShopList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.ItemCount> _item = new global::System.Collections.Generic.List<Bin.ItemCount>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ItemCount> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyShopList")]
  public partial class DailyShopList : global::ProtoBuf.IExtensible
  {
    public DailyShopList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.ItemCount> _item = new global::System.Collections.Generic.List<Bin.ItemCount>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ItemCount> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightBlade")]
  public partial class SoulFightBlade : global::ProtoBuf.IExtensible
  {
    public SoulFightBlade() {}
    
    private uint _bladeid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _sp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sp
    {
      get { return _sp; }
      set { _sp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightBladeList")]
  public partial class SoulFightBladeList : global::ProtoBuf.IExtensible
  {
    public SoulFightBladeList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.SoulFightBlade> _blade = new global::System.Collections.Generic.List<Bin.SoulFightBlade>();
    [global::ProtoBuf.ProtoMember(1, Name=@"blade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulFightBlade> blade
    {
      get { return _blade; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightPlayer")]
  public partial class SoulFightPlayer : global::ProtoBuf.IExtensible
  {
    public SoulFightPlayer() {}
    
    private ulong _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _winFlag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"winFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint winFlag
    {
      get { return _winFlag; }
      set { _winFlag = value; }
    }
    private uint _winCond = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"winCond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint winCond
    {
      get { return _winCond; }
      set { _winCond = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.SoulFightBlade> _blade = new global::System.Collections.Generic.List<Bin.SoulFightBlade>();
    [global::ProtoBuf.ProtoMember(10, Name=@"blade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulFightBlade> blade
    {
      get { return _blade; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightList")]
  public partial class SoulFightList : global::ProtoBuf.IExtensible
  {
    public SoulFightList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.SoulFightPlayer> _player = new global::System.Collections.Generic.List<Bin.SoulFightPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulFightPlayer> player
    {
      get { return _player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightInfo")]
  public partial class SoulFightInfo : global::ProtoBuf.IExtensible
  {
    public SoulFightInfo() {}
    
    private readonly global::System.Collections.Generic.List<Bin.SoulFightPlayer> _player = new global::System.Collections.Generic.List<Bin.SoulFightPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulFightPlayer> player
    {
      get { return _player; }
    }
  
    private readonly global::System.Collections.Generic.List<Bin.SoulFightBlade> _blade = new global::System.Collections.Generic.List<Bin.SoulFightBlade>();
    [global::ProtoBuf.ProtoMember(2, Name=@"blade", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.SoulFightBlade> blade
    {
      get { return _blade; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageChapterRewardUnit")]
  public partial class MessageChapterRewardUnit : global::ProtoBuf.IExtensible
  {
    public MessageChapterRewardUnit() {}
    
    private uint _chapterid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chapterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint chapterid
    {
      get { return _chapterid; }
      set { _chapterid = value; }
    }
    private uint _rewards;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rewards
    {
      get { return _rewards; }
      set { _rewards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageChapterRewards")]
  public partial class MessageChapterRewards : global::ProtoBuf.IExtensible
  {
    public MessageChapterRewards() {}
    
    private readonly global::System.Collections.Generic.List<Bin.MessageChapterRewardUnit> _rewards = new global::System.Collections.Generic.List<Bin.MessageChapterRewardUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MessageChapterRewardUnit> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GiftUnit")]
  public partial class GiftUnit : global::ProtoBuf.IExtensible
  {
    public GiftUnit() {}
    
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GiftList")]
  public partial class GiftList : global::ProtoBuf.IExtensible
  {
    public GiftList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.GiftUnit> _list = new global::System.Collections.Generic.List<Bin.GiftUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.GiftUnit> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDressUnit")]
  public partial class MsgDressUnit : global::ProtoBuf.IExtensible
  {
    public MsgDressUnit() {}
    
    private uint _dressid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dressid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dressid
    {
      get { return _dressid; }
      set { _dressid = value; }
    }
    private uint _lv = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDressUnitList")]
  public partial class MsgDressUnitList : global::ProtoBuf.IExtensible
  {
    public MsgDressUnitList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.MsgDressUnit> _dress = new global::System.Collections.Generic.List<Bin.MsgDressUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MsgDressUnit> dress
    {
      get { return _dress; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgClimbTowerRewardUnit")]
  public partial class MsgClimbTowerRewardUnit : global::ProtoBuf.IExtensible
  {
    public MsgClimbTowerRewardUnit() {}
    
    private uint _key = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint key
    {
      get { return _key; }
      set { _key = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _value = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgClimbTowerRewardList")]
  public partial class MsgClimbTowerRewardList : global::ProtoBuf.IExtensible
  {
    public MsgClimbTowerRewardList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.MsgClimbTowerRewardUnit> _list = new global::System.Collections.Generic.List<Bin.MsgClimbTowerRewardUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MsgClimbTowerRewardUnit> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgActionConf")]
  public partial class MsgActionConf : global::ProtoBuf.IExtensible
  {
    public MsgActionConf() {}
    
    private uint _confid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"confid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint confid
    {
      get { return _confid; }
      set { _confid = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _param = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> param
    {
      get { return _param; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAction")]
  public partial class MsgAction : global::ProtoBuf.IExtensible
  {
    public MsgAction() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Bin.MsgActionConf> _list = new global::System.Collections.Generic.List<Bin.MsgActionConf>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MsgActionConf> list
    {
      get { return _list; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _dones = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dones", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> dones
    {
      get { return _dones; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgActionList")]
  public partial class MsgActionList : global::ProtoBuf.IExtensible
  {
    public MsgActionList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.MsgAction> _actions = new global::System.Collections.Generic.List<Bin.MsgAction>();
    [global::ProtoBuf.ProtoMember(1, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.MsgAction> actions
    {
      get { return _actions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRecharge")]
  public partial class MsgRecharge : global::ProtoBuf.IExtensible
  {
    public MsgRecharge() {}
    
    private readonly global::System.Collections.Generic.List<Bin.ItemCount> _item = new global::System.Collections.Generic.List<Bin.ItemCount>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.ItemCount> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulCoreUnit")]
  public partial class SoulCoreUnit : global::ProtoBuf.IExtensible
  {
    public SoulCoreUnit() {}
    
    private int _maxhp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"maxhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxhp
    {
      get { return _maxhp; }
      set { _maxhp = value; }
    }
    private int _patt = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"patt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int patt
    {
      get { return _patt; }
      set { _patt = value; }
    }
    private int _pdef = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pdef
    {
      get { return _pdef; }
      set { _pdef = value; }
    }
    private int _catt = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"catt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int catt
    {
      get { return _catt; }
      set { _catt = value; }
    }
    private int _cdef = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cdef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cdef
    {
      get { return _cdef; }
      set { _cdef = value; }
    }
    private int _cpstren = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cpstren", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cpstren
    {
      get { return _cpstren; }
      set { _cpstren = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulCoreData")]
  public partial class SoulCoreData : global::ProtoBuf.IExtensible
  {
    public SoulCoreData() {}
    
    private Bin.SoulCoreUnit _total = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"total", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.SoulCoreUnit total
    {
      get { return _total; }
      set { _total = value; }
    }
    private Bin.SoulCoreUnit _cache = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cache", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Bin.SoulCoreUnit cache
    {
      get { return _cache; }
      set { _cache = value; }
    }
    private uint _frees = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"frees", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frees
    {
      get { return _frees; }
      set { _frees = value; }
    }
    private uint _lasttype = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lasttype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lasttype
    {
      get { return _lasttype; }
      set { _lasttype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestFeedBack2Unit")]
  public partial class TestFeedBack2Unit : global::ProtoBuf.IExtensible
  {
    public TestFeedBack2Unit() {}
    
    private uint _itemid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestFeedback2Data")]
  public partial class TestFeedback2Data : global::ProtoBuf.IExtensible
  {
    public TestFeedback2Data() {}
    
    private readonly global::System.Collections.Generic.List<Bin.TestFeedBack2Unit> _gift = new global::System.Collections.Generic.List<Bin.TestFeedBack2Unit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gift", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.TestFeedBack2Unit> gift
    {
      get { return _gift; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserLikeData")]
  public partial class UserLikeData : global::ProtoBuf.IExtensible
  {
    public UserLikeData() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _userid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> userid
    {
      get { return _userid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TitleUnit")]
  public partial class TitleUnit : global::ProtoBuf.IExtensible
  {
    public TitleUnit() {}
    
    private uint _titleid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"titleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint titleid
    {
      get { return _titleid; }
      set { _titleid = value; }
    }
    private uint _cond = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cond
    {
      get { return _cond; }
      set { _cond = value; }
    }
    private uint _flag = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TitleList")]
  public partial class TitleList : global::ProtoBuf.IExtensible
  {
    public TitleList() {}
    
    private readonly global::System.Collections.Generic.List<Bin.TitleUnit> _title = new global::System.Collections.Generic.List<Bin.TitleUnit>();
    [global::ProtoBuf.ProtoMember(1, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bin.TitleUnit> title
    {
      get { return _title; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}