//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: errorcode.proto
// Note: requires additional types generated from: prototype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageErrorCode")]
  public partial class MessageErrorCode : global::ProtoBuf.IExtensible
  {
    public MessageErrorCode() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.ERROR_CODE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.ERROR_CODE_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.EErrorCode _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.EErrorCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EErrorCode")]
    public enum EErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=401014783)]
      FAILED = 401014783,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=400949248)]
      SUCCESS = 400949248,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_ERROR", Value=400949249)]
      DB_ERROR = 400949249,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERSION_ERROR", Value=400949250)]
      VERSION_ERROR = 400949250,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_PARSE_ERROR", Value=400949251)]
      PROTO_PARSE_ERROR = 400949251,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQUENCE_ERROR", Value=400949252)]
      SEQUENCE_ERROR = 400949252,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_IS_BUSY", Value=400949253)]
      SERVER_IS_BUSY = 400949253,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SESSION_OVERDUE", Value=400949254)]
      SESSION_OVERDUE = 400949254,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CROSS_SVR_NOT_FOUND", Value=400949255)]
      CROSS_SVR_NOT_FOUND = 400949255,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SDK_OPT_ERROR", Value=400949505)]
      SDK_OPT_ERROR = 400949505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN_ERROR", Value=400949506)]
      TOKEN_ERROR = 400949506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN_NOT_FOUND", Value=400949507)]
      TOKEN_NOT_FOUND = 400949507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BANK_OPEN_FAILED", Value=400949508)]
      BANK_OPEN_FAILED = 400949508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BANK_CLOSED_FAILED", Value=400949509)]
      BANK_CLOSED_FAILED = 400949509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_ID_ERROR", Value=400949761)]
      USER_ID_ERROR = 400949761,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_TOO_OFTEN", Value=400949762)]
      LOGIN_TOO_OFTEN = 400949762,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_RE_LOGIN", Value=400949763)]
      USER_RE_LOGIN = 400949763,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GATEWAY_NOT_FOUND", Value=400949764)]
      GATEWAY_NOT_FOUND = 400949764,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_KICK_OFF", Value=400949765)]
      SYSTEM_KICK_OFF = 400949765,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONF_ERROR", Value=400950017)]
      CONF_ERROR = 400950017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NAME_EXISTED", Value=400950018)]
      NAME_EXISTED = 400950018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_LV_LIMIT", Value=400950019)]
      USER_LV_LIMIT = 400950019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LV_NOT_ENOUGH", Value=400950020)]
      LV_NOT_ENOUGH = 400950020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIPLV_NOT_ENOUGH", Value=400950021)]
      VIPLV_NOT_ENOUGH = 400950021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CASH_NOT_ENOUGH", Value=400950022)]
      CASH_NOT_ENOUGH = 400950022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_NOT_ENOUGH", Value=400950023)]
      GOLD_NOT_ENOUGH = 400950023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NOT_ENOUGH", Value=400950024)]
      ITEM_NOT_ENOUGH = 400950024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NAME_LEN_INVALID", Value=400950025)]
      NAME_LEN_INVALID = 400950025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTENT_HAVE_DIRTY", Value=400950026)]
      CONTENT_HAVE_DIRTY = 400950026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_TIMES_LIMIT", Value=400950027)]
      MAX_TIMES_LIMIT = 400950027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_TIMES_LIMIT", Value=400950028)]
      DAILY_TIMES_LIMIT = 400950028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_FORBID_TIME", Value=400950029)]
      IN_FORBID_TIME = 400950029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULL_OF_USER", Value=400950030)]
      FULL_OF_USER = 400950030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REWARD_HAVE_GOT", Value=400950031)]
      REWARD_HAVE_GOT = 400950031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ON_CREATING_USER", Value=400950032)]
      ON_CREATING_USER = 400950032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_USER_NUM_LIMIT", Value=400950033)]
      MAX_USER_NUM_LIMIT = 400950033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_SAME_USER_FORBID", Value=400950034)]
      CREATE_SAME_USER_FORBID = 400950034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_NOT_OPEN", Value=400950035)]
      MODULE_NOT_OPEN = 400950035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREETIMES_NOT_ENOUGH", Value=400950036)]
      FREETIMES_NOT_ENOUGH = 400950036,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYTIMES_NOT_ENOUGH", Value=400950037)]
      PAYTIMES_NOT_ENOUGH = 400950037,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_NOT_INIT", Value=400950038)]
      MODULE_NOT_INIT = 400950038,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_LV_LIMIT", Value=400950535)]
      MAX_LV_LIMIT = 400950535,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NOT_FOUND", Value=400950273)]
      ITEM_NOT_FOUND = 400950273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_ITEM_NUM", Value=400950274)]
      MAX_ITEM_NUM = 400950274,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_SELL_FORBID", Value=400950275)]
      ITEM_SELL_FORBID = 400950275,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_SELL_NUM_ERR", Value=400950276)]
      ITEM_SELL_NUM_ERR = 400950276,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_TYPE_ERROR", Value=400950277)]
      ITEM_TYPE_ERROR = 400950277,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_NOT_FOUND", Value=400950529)]
      HERO_NOT_FOUND = 400950529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_STAGE_LIMIT", Value=400950530)]
      MAX_STAGE_LIMIT = 400950530,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_QUALITY_LIMIT", Value=400950531)]
      MAX_QUALITY_LIMIT = 400950531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_STAR_LIMIT", Value=400950532)]
      MAX_STAR_LIMIT = 400950532,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_FIRST", Value=400950533)]
      HERO_STAGE_FIRST = 400950533,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_LV_LIMIT", Value=400950534)]
      HERO_LV_LIMIT = 400950534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_NOT_FOUND", Value=400950785)]
      SHIP_NOT_FOUND = 400950785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CAPTAIN_NOT_FOUND", Value=400950786)]
      CAPTAIN_NOT_FOUND = 400950786,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_ALREADY_EXIST", Value=400950787)]
      SHIP_ALREADY_EXIST = 400950787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_INVALID", Value=400951041)]
      QUEST_INVALID = 400951041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_STARTNPC_ERROR", Value=400951042)]
      QUEST_STARTNPC_ERROR = 400951042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ISDOING", Value=400951043)]
      QUEST_ISDOING = 400951043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_CANNOT_ACCEPT", Value=400951044)]
      QUEST_CANNOT_ACCEPT = 400951044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ACCEPT_FAILED", Value=400951045)]
      QUEST_ACCEPT_FAILED = 400951045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_NOT_DOING", Value=400951046)]
      QUEST_NOT_DOING = 400951046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_NOT_COMPLETE", Value=400951047)]
      QUEST_NOT_COMPLETE = 400951047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ENDNPC_ERROR", Value=400951048)]
      QUEST_ENDNPC_ERROR = 400951048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_REWARD_DROP_ERROR", Value=400951049)]
      QUEST_REWARD_DROP_ERROR = 400951049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWCOUNT_ERROR", Value=400951050)]
      QUEST_DAILYREWCOUNT_ERROR = 400951050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWARD_GET", Value=400951051)]
      QUEST_DAILYREWARD_GET = 400951051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWCOUNT_NOT", Value=400951052)]
      QUEST_DAILYREWCOUNT_NOT = 400951052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWDROP_ERROR", Value=400951053)]
      QUEST_DAILYREWDROP_ERROR = 400951053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_ALREADY_ACCEPTED", Value=400951297)]
      MAIL_ALREADY_ACCEPTED = 400951297,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_NOT_FOUND", Value=400951298)]
      MAIL_NOT_FOUND = 400951298,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_HAVE_EXPIRED", Value=400951299)]
      MAIL_HAVE_EXPIRED = 400951299,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_REQ_INVALID", Value=400954113)]
      GACHA_REQ_INVALID = 400954113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_GOLD_NOT_ENOUGH", Value=400954114)]
      GACHA_GOLD_NOT_ENOUGH = 400954114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_CASH_NOT_ENOUGH", Value=400954115)]
      GACHA_CASH_NOT_ENOUGH = 400954115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_CONF_INVALID", Value=400954116)]
      GACHA_CONF_INVALID = 400954116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_REQ_INVALID", Value=400954369)]
      SHOP_REQ_INVALID = 400954369,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_HAVE_BUY", Value=400954370)]
      GOODS_HAVE_BUY = 400954370
    }
  
}