//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: errorcode.proto
// Note: requires additional types generated from: prototype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageErrorCode")]
  public partial class MessageErrorCode : global::ProtoBuf.IExtensible
  {
    public MessageErrorCode() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.ERROR_CODE_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.ERROR_CODE_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.EErrorCode _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Cmd.EErrorCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EErrorCode")]
    public enum EErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=401014783)]
      FAILED = 401014783,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=400949248)]
      SUCCESS = 400949248,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DB_ERROR", Value=400949249)]
      DB_ERROR = 400949249,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERSION_ERROR", Value=400949287)]
      VERSION_ERROR = 400949287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTO_PARSE_ERROR", Value=400949268)]
      PROTO_PARSE_ERROR = 400949268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEQUENCE_ERROR", Value=400949290)]
      SEQUENCE_ERROR = 400949290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_IS_BUSY", Value=400949256)]
      SERVER_IS_BUSY = 400949256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SESSION_OVERDUE", Value=400949255)]
      SESSION_OVERDUE = 400949255,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CROSS_SVR_NOT_FOUND", Value=400949305)]
      CROSS_SVR_NOT_FOUND = 400949305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SDK_OPT_ERROR", Value=400949257)]
      SDK_OPT_ERROR = 400949257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN_ERROR", Value=400949274)]
      TOKEN_ERROR = 400949274,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOKEN_NOT_FOUND", Value=400949273)]
      TOKEN_NOT_FOUND = 400949273,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BANK_OPEN_FAILED", Value=400949271)]
      BANK_OPEN_FAILED = 400949271,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BANK_CLOSED_FAILED", Value=400949272)]
      BANK_CLOSED_FAILED = 400949272,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_ID_ERROR", Value=400949505)]
      USER_ID_ERROR = 400949505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_TOO_OFTEN", Value=400949506)]
      LOGIN_TOO_OFTEN = 400949506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_RE_LOGIN", Value=400949507)]
      USER_RE_LOGIN = 400949507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GATEWAY_NOT_FOUND", Value=400949508)]
      GATEWAY_NOT_FOUND = 400949508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_KICK_OFF", Value=400949509)]
      SYSTEM_KICK_OFF = 400949509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONF_ERROR", Value=400949250)]
      CONF_ERROR = 400949250,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NAME_EXISTED", Value=400949251)]
      NAME_EXISTED = 400949251,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_ITEM_NUM", Value=400949252)]
      MAX_ITEM_NUM = 400949252,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_LV_LIMIT", Value=400949253)]
      USER_LV_LIMIT = 400949253,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LV_NOT_ENOUGH", Value=400949254)]
      LV_NOT_ENOUGH = 400949254,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VIPLV_NOT_ENOUGH", Value=400949270)]
      VIPLV_NOT_ENOUGH = 400949270,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CASH_NOT_ENOUGH", Value=400949264)]
      CASH_NOT_ENOUGH = 400949264,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_NOT_ENOUGH", Value=400949265)]
      GOLD_NOT_ENOUGH = 400949265,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NOT_ENOUGH", Value=400949302)]
      ITEM_NOT_ENOUGH = 400949302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NAME_LEN_INVALID", Value=400949266)]
      NAME_LEN_INVALID = 400949266,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTENT_HAVE_DIRTY", Value=400949267)]
      CONTENT_HAVE_DIRTY = 400949267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_NOT_FOUND", Value=400949269)]
      ITEM_NOT_FOUND = 400949269,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_TIMES_LIMIT", Value=400949285)]
      MAX_TIMES_LIMIT = 400949285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAILY_TIMES_LIMIT", Value=400949276)]
      DAILY_TIMES_LIMIT = 400949276,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IN_FORBID_TIME", Value=400949277)]
      IN_FORBID_TIME = 400949277,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULL_OF_USER", Value=400949278)]
      FULL_OF_USER = 400949278,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REWARD_HAVE_GOT", Value=400949279)]
      REWARD_HAVE_GOT = 400949279,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ON_CREATING_USER", Value=400949282)]
      ON_CREATING_USER = 400949282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_USER_NUM_LIMIT", Value=400949283)]
      MAX_USER_NUM_LIMIT = 400949283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_SAME_USER_FORBID", Value=400949284)]
      CREATE_SAME_USER_FORBID = 400949284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_NOT_OPEN", Value=400949286)]
      MODULE_NOT_OPEN = 400949286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREETIMES_NOT_ENOUGH", Value=400949291)]
      FREETIMES_NOT_ENOUGH = 400949291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAYTIMES_NOT_ENOUGH", Value=400949292)]
      PAYTIMES_NOT_ENOUGH = 400949292,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_NOT_INIT", Value=400949293)]
      MODULE_NOT_INIT = 400949293,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_NOT_FOUND", Value=400949294)]
      HERO_NOT_FOUND = 400949294,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_SELL_FORBID", Value=400950529)]
      ITEM_SELL_FORBID = 400950529,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_SELL_NUM_ERR", Value=400950531)]
      ITEM_SELL_NUM_ERR = 400950531,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_STAGE_LIMIT", Value=400950785)]
      MAX_STAGE_LIMIT = 400950785,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_FIRST", Value=400950786)]
      HERO_STAGE_FIRST = 400950786,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_QUALITY_LIMIT", Value=400950787)]
      MAX_QUALITY_LIMIT = 400950787,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_STAR_LIMIT", Value=400950788)]
      MAX_STAR_LIMIT = 400950788,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_INVALID", Value=400951041)]
      QUEST_INVALID = 400951041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_STARTNPC_ERROR", Value=400951042)]
      QUEST_STARTNPC_ERROR = 400951042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ISDOING", Value=400951043)]
      QUEST_ISDOING = 400951043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_CANNOT_ACCEPT", Value=400951044)]
      QUEST_CANNOT_ACCEPT = 400951044,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ACCEPT_FAILED", Value=400951045)]
      QUEST_ACCEPT_FAILED = 400951045,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_NOT_DOING", Value=400951046)]
      QUEST_NOT_DOING = 400951046,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_NOT_COMPLETE", Value=400951047)]
      QUEST_NOT_COMPLETE = 400951047,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ENDNPC_ERROR", Value=400951048)]
      QUEST_ENDNPC_ERROR = 400951048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_REWARD_DROP_ERROR", Value=400951049)]
      QUEST_REWARD_DROP_ERROR = 400951049,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWCOUNT_ERROR", Value=400951050)]
      QUEST_DAILYREWCOUNT_ERROR = 400951050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWARD_GET", Value=400951051)]
      QUEST_DAILYREWARD_GET = 400951051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWCOUNT_NOT", Value=400951052)]
      QUEST_DAILYREWCOUNT_NOT = 400951052,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_DAILYREWDROP_ERROR", Value=400951053)]
      QUEST_DAILYREWDROP_ERROR = 400951053,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_ALREADY_ACCEPTED", Value=400951297)]
      MAIL_ALREADY_ACCEPTED = 400951297,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_NOT_FOUND", Value=400951298)]
      MAIL_NOT_FOUND = 400951298,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIL_HAVE_EXPIRED", Value=400951299)]
      MAIL_HAVE_EXPIRED = 400951299,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_REQ_INVALID", Value=400954113)]
      GACHA_REQ_INVALID = 400954113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_GOLD_NOT_ENOUGH", Value=400954114)]
      GACHA_GOLD_NOT_ENOUGH = 400954114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_CASH_NOT_ENOUGH", Value=400954115)]
      GACHA_CASH_NOT_ENOUGH = 400954115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GACHA_CONF_INVALID", Value=400954116)]
      GACHA_CONF_INVALID = 400954116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOP_REQ_INVALID", Value=400954369)]
      SHOP_REQ_INVALID = 400954369,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS_HAVE_BUY", Value=400954370)]
      GOODS_HAVE_BUY = 400954370
    }
  
}