//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fighttype.proto
// Note: requires additional types generated from: prototype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightHit")]
  public partial class FightHit : global::ProtoBuf.IExtensible
  {
    public FightHit() {}
    
    private Cmd.FightUnitInfo _strongman;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strongman", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.FightUnitInfo strongman
    {
      get { return _strongman; }
      set { _strongman = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FightHitInfo> _hitinfo = new global::System.Collections.Generic.List<Cmd.FightHitInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hitinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FightHitInfo> hitinfo
    {
      get { return _hitinfo; }
    }
  
    private int _attackid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"attackid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackid
    {
      get { return _attackid; }
      set { _attackid = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _bulletid = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bulletid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bulletid
    {
      get { return _bulletid; }
      set { _bulletid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightHitInfo")]
  public partial class FightHitInfo : global::ProtoBuf.IExtensible
  {
    public FightHitInfo() {}
    
    private readonly global::System.Collections.Generic.List<Cmd.FightUnitInfo> _weaknesslist = new global::System.Collections.Generic.List<Cmd.FightUnitInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"weaknesslist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FightUnitInfo> weaknesslist
    {
      get { return _weaknesslist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightUnitInfo")]
  public partial class FightUnitInfo : global::ProtoBuf.IExtensible
  {
    public FightUnitInfo() {}
    
    private Cmd.eFightUnitType _unittype = Cmd.eFightUnitType.eFightUnitType_User;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unittype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.eFightUnitType.eFightUnitType_User)]
    public Cmd.eFightUnitType unittype
    {
      get { return _unittype; }
      set { _unittype = value; }
    }
    private ulong _unitid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"unitid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong unitid
    {
      get { return _unitid; }
      set { _unitid = value; }
    }
    private Cmd.eAttackMode _attackmode = Cmd.eAttackMode.eAttackMode_CP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackmode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.eAttackMode.eAttackMode_CP)]
    public Cmd.eAttackMode attackmode
    {
      get { return _attackmode; }
      set { _attackmode = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemUnits")]
  public partial class ItemUnits : global::ProtoBuf.IExtensible
  {
    public ItemUnits() {}
    
    private int _itemid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private int _nums = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nums
    {
      get { return _nums; }
      set { _nums = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropUnits")]
  public partial class PropUnits : global::ProtoBuf.IExtensible
  {
    public PropUnits() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MixUnits")]
  public partial class MixUnits : global::ProtoBuf.IExtensible
  {
    public MixUnits() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulFightBladeCp")]
  public partial class SoulFightBladeCp : global::ProtoBuf.IExtensible
  {
    public SoulFightBladeCp() {}
    
    private uint _bladeid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bladeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bladeid
    {
      get { return _bladeid; }
      set { _bladeid = value; }
    }
    private uint _cp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cp
    {
      get { return _cp; }
      set { _cp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SummonUnit")]
  public partial class SummonUnit : global::ProtoBuf.IExtensible
  {
    public SummonUnit() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _camp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterUnit")]
  public partial class MonsterUnit : global::ProtoBuf.IExtensible
  {
    public MonsterUnit() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _monsterid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monsterid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint monsterid
    {
      get { return _monsterid; }
      set { _monsterid = value; }
    }
    private uint _wave = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wave
    {
      get { return _wave; }
      set { _wave = value; }
    }
    private uint _stageid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stageid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stageid
    {
      get { return _stageid; }
      set { _stageid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector_float")]
  public partial class Vector_float : global::ProtoBuf.IExtensible
  {
    public Vector_float() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnimationInfo")]
  public partial class AnimationInfo : global::ProtoBuf.IExtensible
  {
    public AnimationInfo() {}
    
    private string _state = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string state
    {
      get { return _state; }
      set { _state = value; }
    }
    private float _time = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameSkillData")]
  public partial class FrameSkillData : global::ProtoBuf.IExtensible
  {
    public FrameSkillData() {}
    
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private Cmd.ESkillOperationType _operation_type = Cmd.ESkillOperationType.OPERATION_CLICK;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"operation_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.ESkillOperationType.OPERATION_CLICK)]
    public Cmd.ESkillOperationType operation_type
    {
      get { return _operation_type; }
      set { _operation_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameDataOperation")]
  public partial class FrameDataOperation : global::ProtoBuf.IExtensible
  {
    public FrameDataOperation() {}
    
    private int _directorx = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"directorx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int directorx
    {
      get { return _directorx; }
      set { _directorx = value; }
    }
    private int _directorz = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"directorz", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int directorz
    {
      get { return _directorz; }
      set { _directorz = value; }
    }
    private bool _attack = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private bool _jump = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jump", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool jump
    {
      get { return _jump; }
      set { _jump = value; }
    }
    private bool _roll = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roll", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool roll
    {
      get { return _roll; }
      set { _roll = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameData")]
  public partial class FrameData : global::ProtoBuf.IExtensible
  {
    public FrameData() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private uint _seq = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seq
    {
      get { return _seq; }
      set { _seq = value; }
    }
    private Cmd.FrameDataOperation _frame_operation = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"frame_operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.FrameDataOperation frame_operation
    {
      get { return _frame_operation; }
      set { _frame_operation = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FrameSkillData> _skills = new global::System.Collections.Generic.List<Cmd.FrameSkillData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FrameSkillData> skills
    {
      get { return _skills; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyAction")]
  public partial class KeyAction : global::ProtoBuf.IExtensible
  {
    public KeyAction() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private Cmd.Vector_float _direct = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"direct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Vector_float direct
    {
      get { return _direct; }
      set { _direct = value; }
    }
    private byte[] _keytype = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"keytype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] keytype
    {
      get { return _keytype; }
      set { _keytype = value; }
    }
    private uint _action = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActionPosition")]
  public partial class ActionPosition : global::ProtoBuf.IExtensible
  {
    public ActionPosition() {}
    
    private Cmd.Vector_float _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Vector_float pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _duration = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitState")]
  public partial class UnitState : global::ProtoBuf.IExtensible
  {
    public UnitState() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ActionPosition> _positions = new global::System.Collections.Generic.List<Cmd.ActionPosition>();
    [global::ProtoBuf.ProtoMember(2, Name=@"positions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ActionPosition> positions
    {
      get { return _positions; }
    }
  
    private Cmd.KeyAction _action = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.KeyAction action
    {
      get { return _action; }
      set { _action = value; }
    }
    private Cmd.Vector_float _cur_pos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cur_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Vector_float cur_pos
    {
      get { return _cur_pos; }
      set { _cur_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HpChange")]
  public partial class HpChange : global::ProtoBuf.IExtensible
  {
    public HpChange() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private ulong _releaser = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"releaser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong releaser
    {
      get { return _releaser; }
      set { _releaser = value; }
    }
    private uint _current_hp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_hp
    {
      get { return _current_hp; }
      set { _current_hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBehaviourType")]
    public enum eBehaviourType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBehaviourType_Walk", Value=1)]
      eBehaviourType_Walk = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBehaviourType_Run", Value=2)]
      eBehaviourType_Run = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBehaviourType_Jump", Value=3)]
      eBehaviourType_Jump = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBehaviourType_Direct", Value=4)]
      eBehaviourType_Direct = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBehaviourType_Attack", Value=5)]
      eBehaviourType_Attack = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFightUnitType")]
    public enum eFightUnitType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightUnitType_User", Value=1)]
      eFightUnitType_User = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightUnitType_Monster", Value=2)]
      eFightUnitType_Monster = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eAttackMode")]
    public enum eAttackMode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eAttackMode_CP", Value=1)]
      eAttackMode_CP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eAttackMode_HP", Value=2)]
      eAttackMode_HP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFightScoreLevel")]
    public enum eFightScoreLevel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightScoreLevel_S", Value=1)]
      eFightScoreLevel_S = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightScoreLevel_A", Value=2)]
      eFightScoreLevel_A = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightScoreLevel_B", Value=3)]
      eFightScoreLevel_B = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eFightResult")]
    public enum eFightResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_LOSE", Value=0)]
      eFightResult_LOSE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_WIN", Value=1)]
      eFightResult_WIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_ERROR", Value=2)]
      eFightResult_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_ESCAPE", Value=3)]
      eFightResult_ESCAPE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_FATAL", Value=4)]
      eFightResult_FATAL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eFightResult_INVALID", Value=5)]
      eFightResult_INVALID = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eSummonType")]
    public enum eSummonType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSummonType_Level", Value=1)]
      eSummonType_Level = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSummonType_Skill", Value=2)]
      eSummonType_Skill = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eSummonType_Buff", Value=3)]
      eSummonType_Buff = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EKeyAction")]
    public enum EKeyAction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"IDLE", Value=1)]
      IDLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE", Value=2)]
      MOVE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK1", Value=3)]
      ATTACK1 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK2", Value=4)]
      ATTACK2 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK3", Value=5)]
      ATTACK3 = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ESkillOperationType")]
    public enum ESkillOperationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_CLICK", Value=1)]
      OPERATION_CLICK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_PRESS", Value=2)]
      OPERATION_PRESS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_RELEASE", Value=3)]
      OPERATION_RELEASE = 3
    }
  
}