//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: prototype.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"EMessageID")]
    public enum EMessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TICK_CMD", Value=0)]
      TICK_CMD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TICK_CLIENT_CMD", Value=1)]
      TICK_CLIENT_CMD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CMD", Value=65280)]
      ERROR_CMD = 65280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CODE_S", Value=65281)]
      ERROR_CODE_S = 65281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CMD", Value=256)]
      LOGIN_CMD = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERIFY_VERSION_CS", Value=257)]
      VERIFY_VERSION_CS = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_CS", Value=258)]
      LOGIN_LOGIN_CS = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_SC", Value=259)]
      LOGIN_LOGIN_SC = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_CS", Value=260)]
      LOGIN_GATEW_CS = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_SC", Value=261)]
      LOGIN_GATEW_SC = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CROSS_CS", Value=267)]
      LOGIN_CROSS_CS = 267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CROSS_SC", Value=268)]
      LOGIN_CROSS_SC = 268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_CMD", Value=512)]
      USER_CMD = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_LIST_S", Value=513)]
      USER_LIST_S = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_USER_CS", Value=515)]
      CREATE_USER_CS = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_USER_SC", Value=516)]
      CREATE_USER_SC = 516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_ONLINE_CS", Value=514)]
      USER_ONLINE_CS = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_OFFLINE_CS", Value=534)]
      USER_OFFLINE_CS = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_BASE_DATA_SC", Value=517)]
      USER_BASE_DATA_SC = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_LOAD_OK_S", Value=547)]
      DATA_LOAD_OK_S = 547,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_DATA_CS", Value=635)]
      MODULE_DATA_CS = 635,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MARQUEE_INFO_S", Value=548)]
      MARQUEE_INFO_S = 548,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_CMD", Value=768)]
      ITEM_CMD = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_LIST_S", Value=769)]
      ITEM_LIST_S = 769,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_ITEM_LIST_S", Value=770)]
      UPDATE_ITEM_LIST_S = 770,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE_ITEM_LIST_S", Value=771)]
      REMOVE_ITEM_LIST_S = 771,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_CS", Value=772)]
      SELL_ITEM_CS = 772,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_SC", Value=773)]
      SELL_ITEM_SC = 773,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM_CS", Value=774)]
      USE_ITEM_CS = 774,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM_SC", Value=775)]
      USE_ITEM_SC = 775,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_CMD", Value=1024)]
      HERO_CMD = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_LIST_S", Value=1025)]
      HERO_LIST_S = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_HERO_LIST_S", Value=1026)]
      UPDATE_HERO_LIST_S = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE_HERO_LIST_S", Value=1027)]
      REMOVE_HERO_LIST_S = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_ITEM_2_EXP_CS", Value=1028)]
      HERO_ITEM_2_EXP_CS = 1028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_ITEM_2_EXP_SC", Value=1029)]
      HERO_ITEM_2_EXP_SC = 1029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_UP_CS", Value=1030)]
      HERO_STAGE_UP_CS = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_UP_SC", Value=1031)]
      HERO_STAGE_UP_SC = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_QUALITY_UP_CS", Value=1032)]
      HERO_QUALITY_UP_CS = 1032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_QUALITY_UP_SC", Value=1033)]
      HERO_QUALITY_UP_SC = 1033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAR_UP_CS", Value=1034)]
      HERO_STAR_UP_CS = 1034,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAR_UP_SC", Value=1035)]
      HERO_STAR_UP_SC = 1035,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_CMD", Value=4352)]
      CHAT_CMD = 4352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PRIVATE_CS", Value=4353)]
      CHAT_PRIVATE_CS = 4353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PRIVATE_SC", Value=4354)]
      CHAT_PRIVATE_SC = 4354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_CS", Value=4355)]
      CHAT_WORLD_CS = 4355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_SC", Value=4356)]
      CHAT_WORLD_SC = 4356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_UNION_CS", Value=4358)]
      CHAT_UNION_CS = 4358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_UNION_SC", Value=4359)]
      CHAT_UNION_SC = 4359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_CMD", Value=2304)]
      UTILS_CMD = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_CS", Value=2305)]
      SERVER_TIME_CS = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_SC", Value=2306)]
      SERVER_TIME_SC = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_ECHO", Value=2307)]
      UTILS_ECHO = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_FRAME_DATA_CS", Value=4148)]
      PVP_FRAME_DATA_CS = 4148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_FRAME_ACTION_S", Value=4149)]
      PVP_FRAME_ACTION_S = 4149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_KEY_ACTION_CS", Value=4145)]
      PVP_KEY_ACTION_CS = 4145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_KEY_ACTION_SC", Value=4147)]
      PVP_KEY_ACTION_SC = 4147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_UNIT_INFO_S", Value=4146)]
      PVP_UNIT_INFO_S = 4146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_RESULT_S", Value=4150)]
      PVP_RESULT_S = 4150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_CMD", Value=7168)]
      PVP_CMD = 7168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_CS", Value=7169)]
      PVP_MATCH_CS = 7169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_SC", Value=7171)]
      PVP_MATCH_SC = 7171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_CANCEL_CS", Value=7170)]
      PVP_MATCH_CANCEL_CS = 7170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_INFO_S", Value=7172)]
      BATTLE_INFO_S = 7172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_CLIENT_READY_CS", Value=7173)]
      BATTLE_CLIENT_READY_CS = 7173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_ALL_READY_S", Value=7174)]
      BATTLE_ALL_READY_S = 7174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_COUNTDOWN_S", Value=7175)]
      BATTLE_COUNTDOWN_S = 7175
    }
  
}