//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp.proto
// Note: requires additional types generated from: prototype.proto
// Note: requires additional types generated from: pvptype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchReq")]
  public partial class PvpMatchReq : global::ProtoBuf.IExtensible
  {
    public PvpMatchReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _heroid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private Cmd.eBattleType _battle_type = Cmd.eBattleType.eBattleType_PVP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"battle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.eBattleType.eBattleType_PVP)]
    public Cmd.eBattleType battle_type
    {
      get { return _battle_type; }
      set { _battle_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchCancel")]
  public partial class PvpMatchCancel : global::ProtoBuf.IExtensible
  {
    public PvpMatchCancel() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_CANCEL_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_CANCEL_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchRet")]
  public partial class PvpMatchRet : global::ProtoBuf.IExtensible
  {
    public PvpMatchRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _svrip = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"svrip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] svrip
    {
      get { return _svrip; }
      set { _svrip = value; }
    }
    private int _svrport = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"svrport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int svrport
    {
      get { return _svrport; }
      set { _svrport = value; }
    }
    private uint _tempid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInfoSync")]
  public partial class BattleInfoSync : global::ProtoBuf.IExtensible
  {
    public BattleInfoSync() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_INFO_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_INFO_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FighterInfo> _fighters = new global::System.Collections.Generic.List<Cmd.FighterInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fighters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FighterInfo> fighters
    {
      get { return _fighters; }
    }
  
    private Cmd.eBattleType _battle_type = Cmd.eBattleType.eBattleType_PVP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"battle_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.eBattleType.eBattleType_PVP)]
    public Cmd.eBattleType battle_type
    {
      get { return _battle_type; }
      set { _battle_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleClientReady")]
  public partial class BattleClientReady : global::ProtoBuf.IExtensible
  {
    public BattleClientReady() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_CLIENT_READY_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_CLIENT_READY_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleAllReady")]
  public partial class BattleAllReady : global::ProtoBuf.IExtensible
  {
    public BattleAllReady() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_ALL_READY_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_ALL_READY_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _random_seed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"random_seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint random_seed
    {
      get { return _random_seed; }
      set { _random_seed = value; }
    }
    private uint _frame_sec = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"frame_sec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frame_sec
    {
      get { return _frame_sec; }
      set { _frame_sec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleCountdown")]
  public partial class BattleCountdown : global::ProtoBuf.IExtensible
  {
    public BattleCountdown() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.BATTLE_COUNTDOWN_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.BATTLE_COUNTDOWN_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private ulong _svrtime = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"svrtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong svrtime
    {
      get { return _svrtime; }
      set { _svrtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eBattleType")]
    public enum eBattleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBattleType_PVP", Value=1)]
      eBattleType_PVP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"eBattleType_GVE", Value=2)]
      eBattleType_GVE = 2
    }
  
}