//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvptype.proto
// Note: requires additional types generated from: fighttype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpHeroInfo")]
  public partial class PvpHeroInfo : global::ProtoBuf.IExtensible
  {
    public PvpHeroInfo() {}
    
    private ulong _thisid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"thisid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong thisid
    {
      get { return _thisid; }
      set { _thisid = value; }
    }
    private uint _heroid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private uint _inithp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inithp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inithp
    {
      get { return _inithp; }
      set { _inithp = value; }
    }
    private Cmd.Vector_float _init_pos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"init_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Vector_float init_pos
    {
      get { return _init_pos; }
      set { _init_pos = value; }
    }
    private Cmd.Vector_float _direct = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"direct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.Vector_float direct
    {
      get { return _direct; }
      set { _direct = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FighterInfo")]
  public partial class FighterInfo : global::ProtoBuf.IExtensible
  {
    public FighterInfo() {}
    
    private ulong _uid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.PvpHeroInfo> _heros = new global::System.Collections.Generic.List<Cmd.PvpHeroInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.PvpHeroInfo> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}