//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: user.proto
// Note: requires additional types generated from: prototype.proto
// Note: requires additional types generated from: usertype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserList")]
  public partial class UserList : global::ProtoBuf.IExtensible
  {
    public UserList() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.USER_LIST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.USER_LIST_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.UserBase> _userbase = new global::System.Collections.Generic.List<Cmd.UserBase>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userbase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.UserBase> userbase
    {
      get { return _userbase; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectUserOnline")]
  public partial class SelectUserOnline : global::ProtoBuf.IExtensible
  {
    public SelectUserOnline() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.USER_ONLINE_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.USER_ONLINE_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CurrentUserOffline")]
  public partial class CurrentUserOffline : global::ProtoBuf.IExtensible
  {
    public CurrentUserOffline() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.USER_OFFLINE_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.USER_OFFLINE_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateUserReq")]
  public partial class CreateUserReq : global::ProtoBuf.IExtensible
  {
    public CreateUserReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CREATE_USER_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CREATE_USER_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _usertype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"usertype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int usertype
    {
      get { return _usertype; }
      set { _usertype = value; }
    }
    private byte[] _username;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateUserRet")]
  public partial class CreateUserRet : global::ProtoBuf.IExtensible
  {
    public CreateUserRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CREATE_USER_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CREATE_USER_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.UserBase _userbase;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userbase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.UserBase userbase
    {
      get { return _userbase; }
      set { _userbase = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendUserBaseData")]
  public partial class SendUserBaseData : global::ProtoBuf.IExtensible
  {
    public SendUserBaseData() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.USER_BASE_DATA_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.USER_BASE_DATA_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.UserInfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.UserInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserDataLoadOk")]
  public partial class UserDataLoadOk : global::ProtoBuf.IExtensible
  {
    public UserDataLoadOk() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.DATA_LOAD_OK_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.DATA_LOAD_OK_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameModuleDataReq")]
  public partial class GameModuleDataReq : global::ProtoBuf.IExtensible
  {
    public GameModuleDataReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.MODULE_DATA_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.MODULE_DATA_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _modulelist = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"modulelist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> modulelist
    {
      get { return _modulelist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageMarqueeNotice")]
  public partial class MessageMarqueeNotice : global::ProtoBuf.IExtensible
  {
    public MessageMarqueeNotice() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.MARQUEE_INFO_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.MARQUEE_INFO_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _priority;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private byte[] _content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private uint _interval;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"interval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint interval
    {
      get { return _interval; }
      set { _interval = value; }
    }
    private uint _count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}