//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: chat.proto
// Note: requires additional types generated from: prototype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatPrivateReq")]
  public partial class ChatPrivateReq : global::ProtoBuf.IExtensible
  {
    public ChatPrivateReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CHAT_PRIVATE_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CHAT_PRIVATE_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatWorldReq")]
  public partial class ChatWorldReq : global::ProtoBuf.IExtensible
  {
    public ChatWorldReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CHAT_WORLD_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CHAT_WORLD_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatWorldRet")]
  public partial class ChatWorldRet : global::ProtoBuf.IExtensible
  {
    public ChatWorldRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CHAT_WORLD_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CHAT_WORLD_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private uint _viplv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"viplv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint viplv
    {
      get { return _viplv; }
      set { _viplv = value; }
    }
    private byte[] _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatUnionReq")]
  public partial class ChatUnionReq : global::ProtoBuf.IExtensible
  {
    public ChatUnionReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CHAT_UNION_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CHAT_UNION_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _viplv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"viplv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint viplv
    {
      get { return _viplv; }
      set { _viplv = value; }
    }
    private byte[] _username;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatUnionRet")]
  public partial class ChatUnionRet : global::ProtoBuf.IExtensible
  {
    public ChatUnionRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.CHAT_UNION_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.CHAT_UNION_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private uint _viplv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"viplv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint viplv
    {
      get { return _viplv; }
      set { _viplv = value; }
    }
    private byte[] _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] username
    {
      get { return _username; }
      set { _username = value; }
    }
    private byte[] _text;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}