//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: fight.proto
// Note: requires additional types generated from: prototype.proto
// Note: requires additional types generated from: fighttype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpKeyAction")]
  public partial class PvpKeyAction : global::ProtoBuf.IExtensible
  {
    public PvpKeyAction() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_KEY_ACTION_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_KEY_ACTION_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.KeyAction _action = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.KeyAction action
    {
      get { return _action; }
      set { _action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeyActionSync")]
  public partial class KeyActionSync : global::ProtoBuf.IExtensible
  {
    public KeyActionSync() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_KEY_ACTION_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_KEY_ACTION_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.UnitState> _units = new global::System.Collections.Generic.List<Cmd.UnitState>();
    [global::ProtoBuf.ProtoMember(2, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.UnitState> units
    {
      get { return _units; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitInfoSync")]
  public partial class UnitInfoSync : global::ProtoBuf.IExtensible
  {
    public UnitInfoSync() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_UNIT_INFO_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_UNIT_INFO_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.HpChange> _hp_info = new global::System.Collections.Generic.List<Cmd.HpChange>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hp_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.HpChange> hp_info
    {
      get { return _hp_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpFrameData")]
  public partial class PvpFrameData : global::ProtoBuf.IExtensible
  {
    public PvpFrameData() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_FRAME_DATA_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_FRAME_DATA_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Cmd.FrameData _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Cmd.FrameData data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpFrameActionSync")]
  public partial class PvpFrameActionSync : global::ProtoBuf.IExtensible
  {
    public PvpFrameActionSync() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_FRAME_ACTION_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_FRAME_ACTION_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _svrtime = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"svrtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong svrtime
    {
      get { return _svrtime; }
      set { _svrtime = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.FrameData> _list = new global::System.Collections.Generic.List<Cmd.FrameData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.FrameData> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpResult")]
  public partial class PvpResult : global::ProtoBuf.IExtensible
  {
    public PvpResult() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_RESULT_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_RESULT_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _win = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint win
    {
      get { return _win; }
      set { _win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestReq")]
  public partial class TestReq : global::ProtoBuf.IExtensible
  {
    public TestReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.TEST_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.TEST_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _seqid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seqid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong seqid
    {
      get { return _seqid; }
      set { _seqid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestRet")]
  public partial class TestRet : global::ProtoBuf.IExtensible
  {
    public TestRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.TEST_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.TEST_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _seqid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seqid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong seqid
    {
      get { return _seqid; }
      set { _seqid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrameDataVerify")]
  public partial class FrameDataVerify : global::ProtoBuf.IExtensible
  {
    public FrameDataVerify() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.FRAME_DATA_VERIFY_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.FRAME_DATA_VERIFY_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.VerifySkillData> _data = new global::System.Collections.Generic.List<Cmd.VerifySkillData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.VerifySkillData> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}