//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: gamemodule.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"EGameModule")]
    public enum EGameModule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_USER", Value=1)]
      MODULE_USER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_ITEM", Value=2)]
      MODULE_ITEM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_HERO", Value=3)]
      MODULE_HERO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_SHIP", Value=4)]
      MODULE_SHIP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_EQUIP", Value=5)]
      MODULE_EQUIP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_MAX", Value=63)]
      MODULE_MAX = 63
    }
  
}