//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: prototype.proto
namespace Cmd
{
    [global::ProtoBuf.ProtoContract(Name=@"EMessageID")]
    public enum EMessageID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TICK_CMD", Value=0)]
      TICK_CMD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TICK_CLIENT_CMD", Value=1)]
      TICK_CLIENT_CMD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CMD", Value=65280)]
      ERROR_CMD = 65280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CODE_S", Value=65281)]
      ERROR_CODE_S = 65281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CMD", Value=256)]
      LOGIN_CMD = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERIFY_VERSION_CS", Value=257)]
      VERIFY_VERSION_CS = 257,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_CS", Value=258)]
      LOGIN_LOGIN_CS = 258,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LOGIN_SC", Value=259)]
      LOGIN_LOGIN_SC = 259,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_CS", Value=260)]
      LOGIN_GATEW_CS = 260,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_GATEW_SC", Value=261)]
      LOGIN_GATEW_SC = 261,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CROSS_CS", Value=267)]
      LOGIN_CROSS_CS = 267,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CROSS_SC", Value=268)]
      LOGIN_CROSS_SC = 268,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_CMD", Value=512)]
      USER_CMD = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_LIST_S", Value=513)]
      USER_LIST_S = 513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_USER_CS", Value=515)]
      CREATE_USER_CS = 515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_USER_SC", Value=516)]
      CREATE_USER_SC = 516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_ONLINE_CS", Value=514)]
      USER_ONLINE_CS = 514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_OFFLINE_CS", Value=534)]
      USER_OFFLINE_CS = 534,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_BASE_DATA_SC", Value=517)]
      USER_BASE_DATA_SC = 517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DATA_LOAD_OK_S", Value=547)]
      DATA_LOAD_OK_S = 547,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODULE_DATA_CS", Value=635)]
      MODULE_DATA_CS = 635,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MARQUEE_INFO_S", Value=548)]
      MARQUEE_INFO_S = 548,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_CMD", Value=768)]
      SCENE_CMD = 768,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SCENE_CS", Value=769)]
      ENTER_SCENE_CS = 769,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SCENE_SC", Value=770)]
      ENTER_SCENE_SC = 770,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_CMD", Value=1024)]
      ITEM_CMD = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_LIST_S", Value=1025)]
      ITEM_LIST_S = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_ITEM_LIST_S", Value=1026)]
      UPDATE_ITEM_LIST_S = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE_ITEM_LIST_S", Value=1027)]
      REMOVE_ITEM_LIST_S = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_CS", Value=1028)]
      SELL_ITEM_CS = 1028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELL_ITEM_SC", Value=1029)]
      SELL_ITEM_SC = 1029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM_CS", Value=1030)]
      USE_ITEM_CS = 1030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM_SC", Value=1031)]
      USE_ITEM_SC = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_CMD", Value=1280)]
      HERO_CMD = 1280,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_LIST_S", Value=1281)]
      HERO_LIST_S = 1281,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_HERO_LIST_S", Value=1282)]
      UPDATE_HERO_LIST_S = 1282,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVE_HERO_LIST_S", Value=1283)]
      REMOVE_HERO_LIST_S = 1283,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_ITEM_2_EXP_CS", Value=1284)]
      HERO_ITEM_2_EXP_CS = 1284,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_ITEM_2_EXP_SC", Value=1285)]
      HERO_ITEM_2_EXP_SC = 1285,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_UP_CS", Value=1286)]
      HERO_STAGE_UP_CS = 1286,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAGE_UP_SC", Value=1287)]
      HERO_STAGE_UP_SC = 1287,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_QUALITY_UP_CS", Value=1288)]
      HERO_QUALITY_UP_CS = 1288,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_QUALITY_UP_SC", Value=1289)]
      HERO_QUALITY_UP_SC = 1289,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAR_UP_CS", Value=1290)]
      HERO_STAR_UP_CS = 1290,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HERO_STAR_UP_SC", Value=1291)]
      HERO_STAR_UP_SC = 1291,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_CMD", Value=1536)]
      EQUIP_CMD = 1536,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_LIST_S", Value=1537)]
      EQUIP_LIST_S = 1537,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_LEVEL_UPGRADE_CS", Value=1538)]
      EQUIP_LEVEL_UPGRADE_CS = 1538,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_LEVEL_UPGRADE_SC", Value=1539)]
      EQUIP_LEVEL_UPGRADE_SC = 1539,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_QUALITY_UPGRADE_CS", Value=1540)]
      EQUIP_QUALITY_UPGRADE_CS = 1540,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP_QUALITY_UPGRADE_SC", Value=1541)]
      EQUIP_QUALITY_UPGRADE_SC = 1541,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_CMD", Value=1792)]
      SHIP_CMD = 1792,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_LIST_S", Value=1793)]
      SHIP_LIST_S = 1793,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_UNLOCK_CS", Value=1794)]
      SHIP_UNLOCK_CS = 1794,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_UNLOCK_SC", Value=1795)]
      SHIP_UNLOCK_SC = 1795,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_LEVEL_UP_CS", Value=1796)]
      SHIP_LEVEL_UP_CS = 1796,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_LEVEL_UP_SC", Value=1797)]
      SHIP_LEVEL_UP_SC = 1797,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_BATTLE_START_CS", Value=1798)]
      SHIP_BATTLE_START_CS = 1798,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_BATTLE_START_SC", Value=1799)]
      SHIP_BATTLE_START_SC = 1799,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_BATTLE_RESULT_CS", Value=1800)]
      SHIP_BATTLE_RESULT_CS = 1800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHIP_BATTLE_RESULT_SC", Value=1801)]
      SHIP_BATTLE_RESULT_SC = 1801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_CMD", Value=4352)]
      CHAT_CMD = 4352,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PRIVATE_CS", Value=4353)]
      CHAT_PRIVATE_CS = 4353,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PRIVATE_SC", Value=4354)]
      CHAT_PRIVATE_SC = 4354,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_CS", Value=4355)]
      CHAT_WORLD_CS = 4355,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD_SC", Value=4356)]
      CHAT_WORLD_SC = 4356,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_UNION_CS", Value=4358)]
      CHAT_UNION_CS = 4358,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_UNION_SC", Value=4359)]
      CHAT_UNION_SC = 4359,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_CMD", Value=2304)]
      UTILS_CMD = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_CS", Value=2305)]
      SERVER_TIME_CS = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_TIME_SC", Value=2306)]
      SERVER_TIME_SC = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UTILS_ECHO", Value=2307)]
      UTILS_ECHO = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_FRAME_DATA_CS", Value=4148)]
      PVP_FRAME_DATA_CS = 4148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_FRAME_ACTION_S", Value=4149)]
      PVP_FRAME_ACTION_S = 4149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_KEY_ACTION_CS", Value=4145)]
      PVP_KEY_ACTION_CS = 4145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_KEY_ACTION_SC", Value=4147)]
      PVP_KEY_ACTION_SC = 4147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_UNIT_INFO_S", Value=4146)]
      PVP_UNIT_INFO_S = 4146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_RESULT_S", Value=4150)]
      PVP_RESULT_S = 4150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRAME_DATA_VERIFY_CS", Value=4151)]
      FRAME_DATA_VERIFY_CS = 4151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_CMD", Value=7168)]
      PVP_CMD = 7168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_CS", Value=7169)]
      PVP_MATCH_CS = 7169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_SC", Value=7171)]
      PVP_MATCH_SC = 7171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_CANCEL_CS", Value=7170)]
      PVP_MATCH_CANCEL_CS = 7170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PVP_MATCH_CANCEL_SC", Value=7176)]
      PVP_MATCH_CANCEL_SC = 7176,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_INIT_INFO_S", Value=7172)]
      BATTLE_INIT_INFO_S = 7172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_CLIENT_READY_CS", Value=7173)]
      BATTLE_CLIENT_READY_CS = 7173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_ALL_READY_S", Value=7174)]
      BATTLE_ALL_READY_S = 7174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_COUNTDOWN_S", Value=7175)]
      BATTLE_COUNTDOWN_S = 7175,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_OPEN_MINE_CS", Value=7177)]
      BATTLE_OPEN_MINE_CS = 7177,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_OPEN_MINE_SC", Value=7178)]
      BATTLE_OPEN_MINE_SC = 7178,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_OPEN_MINE_S", Value=7179)]
      BATTLE_OPEN_MINE_S = 7179,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_RESULT_S", Value=7180)]
      BATTLE_RESULT_S = 7180,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEST_SC", Value=7433)]
      TEST_SC = 7433,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEST_CS", Value=7434)]
      TEST_CS = 7434
    }
  
}