//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pvp.proto
// Note: requires additional types generated from: prototype.proto
// Note: requires additional types generated from: pvptype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchReq")]
  public partial class PvpMatchReq : global::ProtoBuf.IExtensible
  {
    public PvpMatchReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _heroid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private Cmd.EBattleType _type = Cmd.EBattleType.BATTLE_TYPE_PVP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EBattleType.BATTLE_TYPE_PVP)]
    public Cmd.EBattleType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchRet")]
  public partial class PvpMatchRet : global::ProtoBuf.IExtensible
  {
    public PvpMatchRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private byte[] _svrip = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"svrip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] svrip
    {
      get { return _svrip; }
      set { _svrip = value; }
    }
    private int _svrport = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"svrport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int svrport
    {
      get { return _svrport; }
      set { _svrport = value; }
    }
    private uint _tempid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tempid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tempid
    {
      get { return _tempid; }
      set { _tempid = value; }
    }
    private ulong _svrtime = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"svrtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong svrtime
    {
      get { return _svrtime; }
      set { _svrtime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchCancel")]
  public partial class PvpMatchCancel : global::ProtoBuf.IExtensible
  {
    public PvpMatchCancel() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_CANCEL_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_CANCEL_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PvpMatchCancelRet")]
  public partial class PvpMatchCancelRet : global::ProtoBuf.IExtensible
  {
    public PvpMatchCancelRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.PVP_MATCH_CANCEL_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.PVP_MATCH_CANCEL_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EBattleType")]
    public enum EBattleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_TYPE_PVP", Value=1)]
      BATTLE_TYPE_PVP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_TYPE_GVE", Value=2)]
      BATTLE_TYPE_GVE = 2
    }
  
}