//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: shiptype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipInfo")]
  public partial class ShipInfo : global::ProtoBuf.IExtensible
  {
    public ShipInfo() {}
    
    private uint _shipid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleAttr")]
  public partial class ShipBattleAttr : global::ProtoBuf.IExtensible
  {
    public ShipBattleAttr() {}
    
    private int _hp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _critical;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"critical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int critical
    {
      get { return _critical; }
      set { _critical = value; }
    }
    private int _imcritical;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"imcritical", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int imcritical
    {
      get { return _imcritical; }
      set { _imcritical = value; }
    }
    private int _hit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _miss;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"miss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miss
    {
      get { return _miss; }
      set { _miss = value; }
    }
    private float _damage;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private float _imdamage;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"imdamage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float imdamage
    {
      get { return _imdamage; }
      set { _imdamage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipHeroInfo")]
  public partial class ShipHeroInfo : global::ProtoBuf.IExtensible
  {
    public ShipHeroInfo() {}
    
    private int _heroid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private int _skillid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private int _randstart;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"randstart", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randstart
    {
      get { return _randstart; }
      set { _randstart = value; }
    }
    private int _randend;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"randend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randend
    {
      get { return _randend; }
      set { _randend = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleInfo")]
  public partial class ShipBattleInfo : global::ProtoBuf.IExtensible
  {
    public ShipBattleInfo() {}
    
    private uint _shipid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private uint _firstvalue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"firstvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint firstvalue
    {
      get { return _firstvalue; }
      set { _firstvalue = value; }
    }
    private uint _power;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint power
    {
      get { return _power; }
      set { _power = value; }
    }
    private uint _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _randMax;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"randMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint randMax
    {
      get { return _randMax; }
      set { _randMax = value; }
    }
    private uint _captainskill;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"captainskill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint captainskill
    {
      get { return _captainskill; }
      set { _captainskill = value; }
    }
    private Cmd.ShipBattleAttr _attr;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Cmd.ShipBattleAttr attr
    {
      get { return _attr; }
      set { _attr = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShipHeroInfo> _heros = new global::System.Collections.Generic.List<Cmd.ShipHeroInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipHeroInfo> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipHitUnit")]
  public partial class ShipHitUnit : global::ProtoBuf.IExtensible
  {
    public ShipHitUnit() {}
    
    private uint _dstpos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dstpos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dstpos
    {
      get { return _dstpos; }
      set { _dstpos = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _hits = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> hits
    {
      get { return _hits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipAttackUnit")]
  public partial class ShipAttackUnit : global::ProtoBuf.IExtensible
  {
    public ShipAttackUnit() {}
    
    private uint _sequenceid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sequenceid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sequenceid
    {
      get { return _sequenceid; }
      set { _sequenceid = value; }
    }
    private int _side;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"side", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int side
    {
      get { return _side; }
      set { _side = value; }
    }
    private uint _srcpos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"srcpos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint srcpos
    {
      get { return _srcpos; }
      set { _srcpos = value; }
    }
    private bool _ismanual;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ismanual", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ismanual
    {
      get { return _ismanual; }
      set { _ismanual = value; }
    }
    private uint _skillid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShipHitUnit> _list = new global::System.Collections.Generic.List<Cmd.ShipHitUnit>();
    [global::ProtoBuf.ProtoMember(6, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipHitUnit> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}