//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ship.proto
// Note: requires additional types generated from: prototype.proto
// Note: requires additional types generated from: shiptype.proto
namespace Cmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendShipList")]
  public partial class SendShipList : global::ProtoBuf.IExtensible
  {
    public SendShipList() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_LIST_S;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_LIST_S)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShipInfo> _list = new global::System.Collections.Generic.List<Cmd.ShipInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipInfo> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipUnlockReq")]
  public partial class ShipUnlockReq : global::ProtoBuf.IExtensible
  {
    public ShipUnlockReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_UNLOCK_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_UNLOCK_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shipid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipUnlockRet")]
  public partial class ShipUnlockRet : global::ProtoBuf.IExtensible
  {
    public ShipUnlockRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_UNLOCK_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_UNLOCK_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shipid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipLevelUpReq")]
  public partial class ShipLevelUpReq : global::ProtoBuf.IExtensible
  {
    public ShipLevelUpReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_LEVEL_UP_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_LEVEL_UP_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shipid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipLevelUpRet")]
  public partial class ShipLevelUpRet : global::ProtoBuf.IExtensible
  {
    public ShipLevelUpRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_LEVEL_UP_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_LEVEL_UP_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _shipid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"shipid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint shipid
    {
      get { return _shipid; }
      set { _shipid = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleStartReq")]
  public partial class ShipBattleStartReq : global::ProtoBuf.IExtensible
  {
    public ShipBattleStartReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_BATTLE_START_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_BATTLE_START_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _levelid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"levelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint levelid
    {
      get { return _levelid; }
      set { _levelid = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _station = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"station", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> station
    {
      get { return _station; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleStartRet")]
  public partial class ShipBattleStartRet : global::ProtoBuf.IExtensible
  {
    public ShipBattleStartRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_BATTLE_START_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_BATTLE_START_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _seed = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint seed
    {
      get { return _seed; }
      set { _seed = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShipBattleInfo> _myships = new global::System.Collections.Generic.List<Cmd.ShipBattleInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"myships", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipBattleInfo> myships
    {
      get { return _myships; }
    }
  
    private readonly global::System.Collections.Generic.List<Cmd.ShipBattleInfo> _opships = new global::System.Collections.Generic.List<Cmd.ShipBattleInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"opships", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipBattleInfo> opships
    {
      get { return _opships; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleResultReq")]
  public partial class ShipBattleResultReq : global::ProtoBuf.IExtensible
  {
    public ShipBattleResultReq() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_BATTLE_RESULT_CS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_BATTLE_RESULT_CS)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _win = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool win
    {
      get { return _win; }
      set { _win = value; }
    }
    private readonly global::System.Collections.Generic.List<Cmd.ShipAttackUnit> _units = new global::System.Collections.Generic.List<Cmd.ShipAttackUnit>();
    [global::ProtoBuf.ProtoMember(3, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Cmd.ShipAttackUnit> units
    {
      get { return _units; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShipBattleResultRet")]
  public partial class ShipBattleResultRet : global::ProtoBuf.IExtensible
  {
    public ShipBattleResultRet() {}
    
    private Cmd.EMessageID _id = Cmd.EMessageID.SHIP_BATTLE_RESULT_SC;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Cmd.EMessageID.SHIP_BATTLE_RESULT_SC)]
    public Cmd.EMessageID id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _win = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool win
    {
      get { return _win; }
      set { _win = value; }
    }
    private bool _cheat = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cheat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool cheat
    {
      get { return _cheat; }
      set { _cheat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}